"""
DOCX rendering service: converts document model to formatted Word documents.
"""
import os
import io
import subprocess
from datetime import datetime
from typing import Any, Dict, List, Optional
from docxtpl import DocxTemplate
from docx.shared import Inches, Pt, RGBColor, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml.ns import qn
from docx.oxml import OxmlElement


# Placeholder marker for missing fields
MISSING_PLACEHOLDER = "[TO BE PROVIDED]"


class DocumentRenderer:
    """Renders document model to DOCX using a master template"""
    
    def __init__(self, template_path: Optional[str] = None):
        self.template_path = template_path
    
    def render(self, doc_model: Dict[str, Any], template_path: Optional[str] = None) -> bytes:
        """
        Render document model to DOCX.
        Returns bytes of the generated document.
        """
        if template_path and os.path.exists(template_path):
            return self._render_from_template(doc_model, template_path)
        else:
            return self._render_from_scratch(doc_model)
    
    def _render_from_template(self, doc_model: Dict[str, Any], template_path: str) -> bytes:
        """Render using a docxtpl template"""
        doc = DocxTemplate(template_path)
        
        # Build context for template
        context = self._build_template_context(doc_model)
        doc.render(context)
        
        buffer = io.BytesIO()
        doc.save(buffer)
        buffer.seek(0)
        return buffer.read()
    
    def _render_from_scratch(self, doc_model: Dict[str, Any]) -> bytes:
        """Render a clean document without a template"""
        from docx import Document
        
        doc = Document()
        
        # Set margins
        for section in doc.sections:
            section.top_margin = Cm(2.54)
            section.bottom_margin = Cm(2.54)
            section.left_margin = Cm(2.54)
            section.right_margin = Cm(2.54)
        
        # Document header
        doc.add_heading("Accreditation Report", 0)
        
        # Template info
        p = doc.add_paragraph()
        p.add_run(f"Template: {doc_model.get('template_id', 'N/A')}").bold = True
        p.add_run(f" | Version: {doc_model.get('template_version', 'N/A')}")
        p.add_run(f" | Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
        
        # Add footer with template info
        footer = doc.sections[0].footer
        footer_para = footer.paragraphs[0]
        footer_para.text = f"Generated by AccreditDraft | {doc_model.get('template_id', '')} v{doc_model.get('template_version', '')}"
        
        doc.add_paragraph()  # spacer
        
        # Render sections
        for section in doc_model.get("sections", []):
            self._render_section(doc, section)
        
        buffer = io.BytesIO()
        doc.save(buffer)
        buffer.seek(0)
        return buffer.read()
    
    def _render_section(self, doc, section: Dict[str, Any]):
        """Render a single section"""
        # Section heading
        doc.add_heading(section.get("title", "Section"), level=1)
        
        fields = section.get("fields", {})
        if isinstance(fields, dict):
            for field_id, field_data in fields.items():
                self._render_field(doc, field_id, field_data)
    
    def _render_field(self, doc, field_id: str, field_data: Any):
        """Render a single field"""
        if isinstance(field_data, dict):
            value = field_data.get("edited_value") or field_data.get("value")
            status = field_data.get("status", "auto")
            label = field_data.get("label", field_id.replace("_", " ").title())
        else:
            value = field_data
            status = "auto"
            label = field_id.replace("_", " ").title()
        
        # Format label
        p = doc.add_paragraph()
        run = p.add_run(f"{label}: ")
        run.bold = True
        
        if value is None or status == "missing":
            # Missing placeholder
            missing_run = p.add_run(MISSING_PLACEHOLDER)
            missing_run.font.color.rgb = RGBColor(255, 0, 0)  # Red
        elif isinstance(value, list):
            # Render list items
            for i, item in enumerate(value):
                item_p = doc.add_paragraph(style="List Bullet")
                item_p.add_run(str(item))
        elif isinstance(value, dict):
            # Complex value
            for k, v in value.items():
                item_p = doc.add_paragraph()
                item_p.add_run(f"{k}: ").bold = True
                item_p.add_run(str(v))
        else:
            p.add_run(str(value))
    
    def _build_template_context(self, doc_model: Dict[str, Any]) -> Dict[str, Any]:
        """Build context dict for docxtpl template"""
        context = {
            "template_id": doc_model.get("template_id", ""),
            "template_version": doc_model.get("template_version", ""),
            "generated_date": datetime.now().strftime("%Y-%m-%d %H:%M"),
            "sections": [],
        }
        
        for section in doc_model.get("sections", []):
            section_data = {
                "title": section.get("title", ""),
                "fields": {},
            }
            
            fields = section.get("fields", {})
            if isinstance(fields, dict):
                for field_id, field_data in fields.items():
                    if isinstance(field_data, dict):
                        value = field_data.get("edited_value") or field_data.get("value")
                        status = field_data.get("status", "auto")
                    else:
                        value = field_data
                        status = "confirmed"
                    
                    # Format value for template
                    if value is None or status == "missing":
                        section_data["fields"][field_id] = MISSING_PLACEHOLDER
                        section_data["fields"][f"{field_id}_missing"] = True
                    elif isinstance(value, list):
                        section_data["fields"][field_id] = "; ".join(str(v) for v in value)
                    else:
                        section_data["fields"][field_id] = str(value)
            
            context["sections"].append(section_data)
        
        return context
    
    def add_page_numbers(self, doc_bytes: bytes) -> bytes:
        """Add page numbers to document using raw XML"""
        from docx import Document
        from docx.oxml.ns import qn
        from docx.oxml import OxmlElement
        
        doc = Document(io.BytesIO(doc_bytes))
        
        # Add page number field to footer
        for section in doc.sections:
            footer = section.footer
            footer.is_linked_to_previous = False
            
            para = footer.paragraphs[0]
            para.alignment = WD_ALIGN_PARAGRAPH.CENTER
            
            # Add "Page " text
            run = para.add_run("Page ")
            
            # Add page number field
            fldChar1 = OxmlElement("w:fldChar")
            fldChar1.set(qn("w:fldCharType"), "begin")
            
            instrText = OxmlElement("w:instrText")
            instrText.set(qn("xml:space"), "preserve")
            instrText.text = "PAGE"
            
            fldChar2 = OxmlElement("w:fldChar")
            fldChar2.set(qn("w:fldCharType"), "separate")
            
            fldChar3 = OxmlElement("w:fldChar")
            fldChar3.set(qn("w:fldCharType"), "end")
            
            run._r.append(fldChar1)
            run._r.append(instrText)
            run._r.append(fldChar2)
            run._r.append(fldChar3)
            
            # Add " of " text
            para.add_run(" of ")
            
            # Add NUMPAGES field
            run2 = para.add_run()
            fldChar4 = OxmlElement("w:fldChar")
            fldChar4.set(qn("w:fldCharType"), "begin")
            instrText2 = OxmlElement("w:instrText")
            instrText2.set(qn("xml:space"), "preserve")
            instrText2.text = "NUMPAGES"
            fldChar5 = OxmlElement("w:fldChar")
            fldChar5.set(qn("w:fldCharType"), "separate")
            fldChar6 = OxmlElement("w:fldChar")
            fldChar6.set(qn("w:fldCharType"), "end")
            run2._r.append(fldChar4)
            run2._r.append(instrText2)
            run2._r.append(fldChar5)
            run2._r.append(fldChar6)
        
        buffer = io.BytesIO()
        doc.save(buffer)
        buffer.seek(0)
        return buffer.read()


def convert_docx_to_pdf(docx_bytes: bytes) -> Optional[bytes]:
    """
    Convert DOCX to PDF using LibreOffice headless.
    Returns PDF bytes or None if conversion fails.
    """
    try:
        # Write DOCX to temp file
        import tempfile
        import os
        
        with tempfile.NamedTemporaryFile(suffix=".docx", delete=False) as tmp_docx:
            tmp_docx.write(docx_bytes)
            docx_path = tmp_docx.name
        
        pdf_path = docx_path.replace(".docx", ".pdf")
        
        # Run LibreOffice conversion
        result = subprocess.run(
            ["libreoffice", "--headless", "--convert-to", "pdf", "--outdir", os.path.dirname(pdf_path), docx_path],
            capture_output=True,
            timeout=60,
        )
        
        if result.returncode == 0 and os.path.exists(pdf_path):
            with open(pdf_path, "rb") as f:
                pdf_bytes = f.read()
            
            # Cleanup
            os.unlink(docx_path)
            os.unlink(pdf_path)
            
            return pdf_bytes
        else:
            print(f"LibreOffice conversion failed: {result.stderr.decode()}")
            return None
    
    except FileNotFoundError:
        print("LibreOffice not found. PDF conversion unavailable.")
        return None
    except Exception as e:
        print(f"PDF conversion error: {e}")
        return None


# Singleton
_renderer: DocumentRenderer = None


def get_renderer() -> DocumentRenderer:
    global _renderer
    if _renderer is None:
        _renderer = DocumentRenderer()
    return _renderer